### ISSUE TITLE
Narrow suggestions in `when` and `unless` clauses

### ISSUE THREAD

**Issue by chrnorm** [cedar-policy/vscode-cedar#19]
### Category

Cedar editing features

### Describe the feature you'd like to request

A way to “narrow” the suggestions offered by the extension in the when/unless clauses would be fantastic. 

See attached screenshot - in the particular example I assert that resource is `GCP::ProjectGrant`, so ideally I would only see autocomplete suggestions pertaining the `GCP::ProjectGrant` resource. 

This is a pain point for us because we have actions that can apply to many resource types, so it makes the autocomplete quite noisy.

![image (41)](https://github.com/cedar-policy/vscode-cedar/assets/17420369/6ecdb7c5-d267-49f8-b3e6-b591de654c9a)

### Describe alternatives you've considered

Currently the workaround is to look through the list of suggestions and find the matching entity type on the right side of the selector dropdown.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by hakanson** [comment]
- Fixed in #18 and part of release v0.6.2.
- Working on changes for upcoming Cedar 3.x pre-release version

**Comment by hakanson** [comment]
fixed in #20 for pre-release v0.7.2
