### ISSUE TITLE
is operator does not work

### ISSUE THREAD

**Issue by CosimoMatassini** [cedar-policy/vscode-cedar#27]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/vscode-cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/vscode-cedar/blob/main/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Policy Editing

### Describe the bug

The is operator does not work: it is not recognized.
This issue is present in the playground as well.

### Expected behavior

Fix this

### Reproduction steps

The simplest way to reproduce the issue is to copy the tinytodo application schema to the playground and use a policy with the is operator. 

### Code Snippet

permit (
  principal,
  action,
  resource is List
)
when { resource.owner == principal };

### Log output

```
// Put your output below this line
Policy syntax is invalid
unexpected token `is`
invalid token
```

### Visual Studio Code version

1.92.0

### Cedar policy language extension version

0.6.4

### Additional information and screenshots

This problem occurs with the other versions of the extension as well, including 0.7.6

**Comment by khieta** [comment]
Hi, thanks for your interest in Cedar! The issue is that the `is` operator was added as part of Cedar version 3.0, which IIRC is only supported in a pre-release version of the vscode plugin. See #10 for more details.
